# Generated by Django 3.2.8 on 2021-11-15 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='defaul.jpg', upload_to='images')),
                ('company_name', models.TextField(blank=True, max_length=100)),
                ('valid_seller', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemListed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='itemImages')),
                ('item_detail', models.TextField(max_length=255)),
                ('likes', models.IntegerField(verbose_name='likes')),
                ('discount_ammount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('user_iden', models.CharField(max_length=150)),
                ('comments', models.CharField(max_length=150)),
                ('ItemListed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.itemlisted')),
            ],
        ),
    ]
