# Generated by Django 3.2.8 on 2021-11-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='item_name',
        ),
    ]
