# Generated by Django 3.2.8 on 2021-11-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_comment_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisted',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=6),
        ),
        migrations.AddField(
            model_name='itemlisted',
            name='size',
            field=models.CharField(choices=[('infant', 'infant'), ('Small', 'Samll'), ('Medium', 'Medium'), ('Large', 'Large'), ('Xl', 'Xl'), ('XXL', 'XXl')], default='Medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
