# Generated by Django 3.2.8 on 2021-11-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20211115_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlisted',
            name='size',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemlisted',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='itemlisted',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemlisted',
            name='discount_ammount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemlisted',
            name='item_detail',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
