# Generated by Django 3.2.8 on 2021-11-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(default='Z:/Django/usercreationform/prac/image/images/default.png', upload_to='images'),
        ),
    ]
