# Generated by Django 3.2.8 on 2021-11-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.itemlisted'),
        ),
    ]
